### ISSUE TITLE
Division by zero error

### ISSUE THREAD

**Issue by svale** [nystudio107/craft-imageoptimize-imgix#3]
### Describe the bug
A single uploaded image (7360 × 4912 JPG), that for some unknown reason would not be manipulated ("This is not an image that could be manipulated or the images would all be upscaled") then afterwards crashes the Assets view because it creates a `Division by zero error` on line 146 in `ImgixImageTransform.php`:

```
if ($settings->autoSharpenScaledImages) {
    // See if the image has been scaled >= 50%
    $widthScale = (int)((($transform->width ?? $asset->getWidth()) / $asset->getWidth()) * 100);
    $heightScale =  (int)((($transform->height ?? $asset->getHeight()) / $asset->getHeight()) * 100);
    if (($widthScale >= (int)$settings->sharpenScaledImagePercentage) || ($heightScale >= (int)$settings->sharpenScaledImagePercentage)) {
        $params['usm'] = (int)($this->unsharpMask ?? 25);
    }
}
```

This is probably a bit of an edge case, as I assume the image somehow has been corrupted while being uploaded.  
And it was relatively easily fixed by first turning of `autoSharpenScaledImages` and the re-uploading the image, before re-applying `autoSharpenScaledImages`. 

But the issue breaks the entire Assets view in Craft CMS until fixed which is a bit unfortunate for the client.

Would it be possible to add a simple defensive check around the divisions? E.g
```
if($asset->getWidth() && $asset->getHeight()) {
 ...   
}
```
I'd be happy to open a PR if it will be considered.

### To reproduce
Steps to reproduce the behaviour:
1. Upload and image that will not be resized (can be tricky)
2. Open the Assets view in Craft CSM
3. See "Server Error Message" with details in Network tab 

### Expected behaviour
An assets directory that lists images also if some are corrupted and where it then is possible to delte/replace the broken image

### Screenshots
<img width="992" alt="Screenshot 2021-11-25 at 12 36 29" src="https://user-images.githubusercontent.com/5339180/143441552-5bfd6509-999e-4033-8b5d-6fab91f68907.png">
<img width="571" alt="Screenshot 2021-11-25 at 13 02 27" src="https://user-images.githubusercontent.com/5339180/143441565-1f2140d2-64e9-40f1-8b29-0f938f852143.png">

### Versions
- Plugin version:
     - ImageOptimize 1.6.38
     - craft-imageoptimize-imgix: 1.2.3
- Craft version: 3.7.21

_As always -thank your for providing superb plugins!_

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-imageoptimize-imgix/commit/4d14fe9d36cc7add443c56cd11857ee0f350a125
